### ISSUE TITLE
Why Nosetests rather than PyTest?

### ISSUE THREAD

**Issue by SethMichaelLarson** [SethMichaelLarson/python_project_template#2]
I figure I'm going to get this question so I'll preemptively answer.
I prefer `nose` module for testing over `pytest`. Blasphemy to the Python community, I'm aware, but it is what I'm used to and most productive with.

If you want to use `pytest` instead of `nose` do the following:

* Remove nose from `dev-requirements.txt` and replace with `pytest` and `pytest-cov`.
* Change the `setup.cfg` to `pytest`.
* Within `tox.ini` replace the `nosetests` command with `pytest`.

Should work, if you have any trouble just ask in this issue or make another issue.
Thanks.

**Comment by jayfk** [comment]
> If you want to use pytest instead of nose do the following:

*or* you could make it an option in cookiecutter and clean up files with a post-gen hook. 

Cookiecutter Django is using this a lot, take a look at [post_gen_project.py](https://github.com/pydanny/cookiecutter-django/blob/master/hooks/post_gen_project.py). The basic idea is to create files for each option and then remove the files that are no longer needed.

**Comment by SethMichaelLarson** [comment]
Great idea! I'll look at this! :) Thanks!

**Comment by SethMichaelLarson** [comment]
I've been convinced by the community to add PyTest as an optional setting :) Look forward to seeing it soon!
