### ISSUE TITLE
More code analysis tools

### ISSUE THREAD

**Issue by SylvainDe** [SethMichaelLarson/python_project_template#3]
As you are using CodeClimate, you might also be interested in using the following services:

 - https://landscape.io
 - https://www.quantifiedcode.com
 - https://scrutinizer-ci.com
 - https://www.codacy.com

**Comment by SethMichaelLarson** [comment]
These are definitely good options as well! I'm most familiar with CodeClimate but I'm sure all of these code quality services could be easily added or swapped in. :) Thanks for making a list!

**Comment by SethMichaelLarson** [comment]
It really is a shame that templates can't be more modular. :) I would definitely look into adding all of these if they were!
