### ISSUE TITLE
Add setuptools_scm

### ISSUE THREAD

**Issue by ksindi** [SethMichaelLarson/python_project_template#4]
Awesome idea! In case you haven't come across it yet, I highly recommend [setuptools_scm](https://github.com/pypa/setuptools_scm) for managing versions.

**Comment by SethMichaelLarson** [comment]
Thanks for the suggestion! I will take a look at this today and try to add it! :)

**Comment by SethMichaelLarson** [comment]
I probably won't be adding this to the template explicitly. It's definitely compatible but I feel that if this module is wanted by the developer it should be easy enough to add. :) Thanks for the suggestion.
