### ISSUE TITLE
Setup.py should use setuptools.find_packages()

### ISSUE THREAD

**Issue by triplepoint** [SethMichaelLarson/python_project_template#5]
Currently "packages" is an empty list.

**Comment by triplepoint** [comment]
Have a look at http://setuptools.readthedocs.io/en/latest/setuptools.html#basic-use for more info

**Comment by SethMichaelLarson** [comment]
You're right that I could use `find_packages`. The reason I don't is because it doesn't pick up packages that start with underscores which I use in my projects for private packages.

**Comment by SethMichaelLarson** [comment]
I'll swap to using `find_packages`. I was aware that it exists and it's function but I prefer to edit the packages fields manually.

**Comment by SethMichaelLarson** [comment]
Added this with the latest patch.
