### ISSUE TITLE
Requirements.txt should not be read in as setup.py's "install_requires"

### ISSUE THREAD

**Issue by triplepoint** [SethMichaelLarson/python_project_template#6]
These two concepts aren't the same thing.

For reference, https://caremad.io/posts/2013/07/setup-vs-requirement/

**Comment by SethMichaelLarson** [comment]
Sadly PyUp only updates requirements.txt so I've deduplicated the information where I can. Pinning the version of dependencies is better than allowing arbitrary upgrades in dependencies breaking functionality.

**Comment by SethMichaelLarson** [comment]
This can be handled by users of the template. The only reason I use requirements.txt at all is for PyUp dependency tracking.
