### ISSUE TITLE
License should be parameterized

### ISSUE THREAD

**Issue by triplepoint** [SethMichaelLarson/python_project_template#8]
Assuming the project is using the MIT license is trouble, if the author forgets to edit the field after the template is rendered.

The License name and content could be pulled out into default template values.

**Comment by SethMichaelLarson** [comment]
I use MIT for all my projects hence it's inclusion. I've noted in the README that the license should change if a non-MIT license is desired. I would consider removing it from the template.

**Comment by SethMichaelLarson** [comment]
I added better notes about where to change if you're using a non-MIT license to the README and parameterized the `license` parameter in `setup` to come from `__init__.__license__`.
